### ISSUE TITLE
Missing file in the 2D evaluation

### ISSUE THREAD

**Issue by sachabinder** [OllieBoyne/FIND#2]
Hi,

First of all, I would like to thank you for your work and for the clarity of your code. 

It seems that the file `eval_metric.py` is missing at [`/src/eval`](https://github.com/OllieBoyne/FIND/tree/main/src/eval). Indeed, in module importation on the 2D evaluation, some modules are missing :
https://github.com/OllieBoyne/FIND/blob/34e34afd78c3d37b95e0417ffffd93a711f68389/src/eval/eval_2d.py#L27

Finally, there seems to be a small typo :
https://github.com/OllieBoyne/FIND/blob/34e34afd78c3d37b95e0417ffffd93a711f68389/README.md?plain=1#L39
```suggestion
python src/eval/eval_3d.py --exp_name 3D_only
```

Thanks again for your work.

**Comment by OllieBoyne** [comment]
I have just pushed a commit which added the missing file, and corrected the typo. Please let me know if any further issues with the evaluation - thanks!
